services:
  composer:
    image: docker.io/library/composer:2.8.12
    working_dir: /app
    volumes:
      - ${PWD}:/app:z

    # command: ["composer", "update"]
    command: ["tail", "-f", "/dev/null"]

    stdin_open: true
    tty: true
